# Generated by Django 5.2.2 on 2025-08-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodehoras',
            name='horas',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
